-- MySQL Script generated by MySQL Workbench
-- Sat Apr 13 15:45:10 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------


-- -----------------------------------------------------
-- Table `mydb`.`telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS telefone (
  idtelefone INT UNSIGNED NOT NULL AUTO_INCREMENT,
  ddd VARCHAR(45) NOT NULL,
  digitos VARCHAR(45) NOT NULL,
  PRIMARY KEY (idtelefone)
);


-- -----------------------------------------------------
-- Table `usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS usuario (
  idusuario INT UNSIGNED NOT NULL AUTO_INCREMENT,
  nome VARCHAR(45) NOT NULL,
  sobrenome VARCHAR(45) NOT NULL,
  rua VARCHAR(45) NOT NULL,
  bairro VARCHAR(45) NOT NULL,
  cidade VARCHAR(45) NOT NULL,
  estado VARCHAR(45) NOT NULL,
  telefone_idtelefone INT UNSIGNED NULL,
  PRIMARY KEY (idusuario, telefone_idtelefone),
  INDEX fk_usuario_telefone1_idx (telefone_idtelefone ASC),
  CONSTRAINT fk_usuario_telefone1
    FOREIGN KEY (telefone_idtelefone)
    REFERENCES telefone (idtelefone)
    ON DELETE SET NULL
    ON UPDATE CASCADE
);


-- -----------------------------------------------------
-- Table `mydb`.`autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS autor (
  idautor INT UNSIGNED NOT NULL AUTO_INCREMENT,
  nome VARCHAR(45) NOT NULL,
  sobrenome VARCHAR(45) NOT NULL,
  nacionalidade VARCHAR(45) NULL,
  PRIMARY KEY (idautor)
);


-- -----------------------------------------------------
-- Table `mydb`.`editora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS editora (
  nome VARCHAR(50) NOT NULL,
  rua VARCHAR(45) NOT NULL,
  bairro VARCHAR(45) NOT NULL,
  cidade VARCHAR(45) NOT NULL,
  estado VARCHAR(45) NOT NULL,
  PRIMARY KEY (nome)
);


-- -----------------------------------------------------
-- Table `mydb`.`obra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS obra (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  titulo VARCHAR(45) NOT NULL,
  classificasao VARCHAR(45) NOT NULL,
  idioma VARCHAR(45) NOT NULL,
  ISBN VARCHAR(45) NOT NULL,
  ano_publicasao VARCHAR(45) NOT NULL,
  edisao VARCHAR(45) NOT NULL,
  autor_idautor INT UNSIGNED NOT NULL,
  editora_nome VARCHAR(50) NOT NULL,
  PRIMARY KEY (id),
  INDEX fk_obra_autor_idx (autor_idautor ASC) ,
  INDEX fk_obra_editora1_idx (editora_nome ASC) ,
  CONSTRAINT fk_obra_autor
    FOREIGN KEY (autor_idautor)
    REFERENCES autor (idautor)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT fk_obra_editora1
    FOREIGN KEY (editora_nome)
    REFERENCES editora (nome)
    ON DELETE NO ACTION
    ON UPDATE CASCADE
);


-- -----------------------------------------------------
-- Table `mydb`.`emprestimo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS emprestimo (
  usuario_idusuario INT UNSIGNED NOT NULL,
  obra_id INT UNSIGNED NOT NULL,
  data DATE NOT NULL,
  data_marcada_devolver DATETIME NOT NULL,
  PRIMARY KEY (usuario_idusuario, obra_id),
  INDEX fk_usuario_has_obra_obra1_idx (obra_id ASC) ,
  INDEX fk_usuario_has_obra_usuario1_idx (usuario_idusuario ASC) ,
  CONSTRAINT fk_usuario_has_obra_usuario1
    FOREIGN KEY (usuario_idusuario)
    REFERENCES usuario (idusuario)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT fk_usuario_has_obra_obra1
    FOREIGN KEY (obra_id)
    REFERENCES obra (id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
);
